# Generated by Django 5.2.4 on 2025-08-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutcontent_herosection_impactstat_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='staff_photos/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
