# Generated by Django 5.2.4 on 2025-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='Child',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='loaction',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
