# Generated by Django 5.2.4 on 2025-08-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_child_donation_child_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressreport',
            old_name='Child',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
